### ISSUE TITLE
Output file timestamps

### ISSUE THREAD

**Issue by thezim** [ehendrix23/tesla_dashcam#119]
It would be nice the the final file output had its file system date time stamp set to the video's timestamp. I wrote the below Powershell script to do it form, but would be nice it was done automatically for me.

``` powershell
$files = Get-ChildItem -Path "~/Movies/Tesla_Dashcam"
foreach($file in $files){
    $date = $file.BaseName -split "_" | Select-Object -Last 1
    $filedate = [DateTime]::ParseExact($date, "yyyy-MM-ddTHH-mm-ss", [CultureInfo]::InvariantCulture)
    $file.LastWriteTime = $filedate
    $file.CreationTime = $filedate
    $file.LastAccessTime = $filedate
}
```

**Comment by ehendrix23** [comment]
The filename itself for each event (folder) is based on the start & end timestamps for the event. Putting the timestamp of the final file(s) to video timestamp can mean breaking things people do as they might have things based on when the final video was created by the script instead.
Further, some would then want to have it based on start of the event and others for the end of the event.

**Comment by thezim** [comment]
Can it be optional then? Start or stop.

**Comment by ehendrix23** [comment]
New parameter: --set_moviefile_timestamp with optional values START and STOP.
If you do not provide this parameter then behavior is same as now. When providing this parameter without any further value it will default to START. Otherwise it will be the start or stop based on what you provided.

The timestamp will be set on the event movie files based on the start/stop of that event. If you create a merged video file (multiple events combined) then it will be based on the start of the earliest event or stop of the latest event (based on START or STOP).

Does that work?

**Comment by ehendrix23** [comment]
One last thing, right now it will set last modified but not create. Mainly cause the default call for that in Python does not have the option to set creation date as that is not kept in Unix (but clearly in Windows). Figuring this should not be a problem and would actually allow you in Windows to see when the movie file itself was created (creation date) compared to when the event timestamp is from (last modified).

**Comment by thezim** [comment]
That all seems reasonable to me.

**Comment by ehendrix23** [comment]
Closing. Next version will have this (already in dev).
