### ISSUE TITLE
Raspberry Pi 4

### ISSUE THREAD

**Issue by appark** [ehendrix23/tesla_dashcam#120]
Can this run on a pi 4?

**Comment by ehendrix23** [comment]
It should be able to but if I recall correctly without hardware acceleration (might be wrong).

**Comment by appark** [comment]
without hardware acceleration?

**Comment by tux-o-matic** [comment]
The Raspberry Pi (not just the 4) can do h264 offloading to the GPU both for decoding and encoding (ffmpeg mmal and omx ).
This won't do real time 1080p 30 fps handling but at least it frees resources on the CPU. 
The more you offload to the GPU, the more RAM you need to assign to it.

**Comment by GertVil** [comment]
Does anyone have any idea on how fast it would be?

**Comment by chrisalmy** [comment]
I'm running it on my RPi4 with 2Gig of RAM now. I'm also running OMV as well as it handles my NAS which consists of a USB attached hard drive (where all the video files are located). A couple of things to note:
You'll need to install FFMPEG, Python 3.7, and PIP.
The timestamp font is missing, so I just run without timestamps.
I run with GPU set to RPi and CPU load runs around 40% while running.
The system has a cooling fan that constantly blows air over it and the CPU runs around 55C. No alerts by the system regarding temperature.
Running in ultrafast (minimal compression) it takes about 20-25 minutes per 30 minute Sentry event.
My original 2.4 amp power supply overloaded after about 10 minutes of processing and powered off the Pi. I switched to a 3.5 amp power supply and then it ran this for hours with no issues.

Overall I'm happy to see it works and I don't have to do this on a PC. I'll set this up as a cron job so every night it will run and process any new videos uploaded by my Raspberry Pi Zero W in the car so I can then review the next day if needed. I then run another cron job that will then auto purge these videos after a few months to keep the drive from filling up.

**Comment by simonrb2000** [comment]
How did you set this up on a raspberry pi? 

Cheers

**Comment by chrisalmy** [comment]
It's been a while since I did this, but from memory, I had to do the following.
Install Python3 using these directions: https://samx18.io/blog/2018/09/05/python3_raspberrypi.html 
Install PIP with the command: sudo apt install python3-pip
Install FFMPEG with the command: sudo apt-get install ffmpeg
Finally, install the Tesla Dashcam software with the command: python3 -m pip install tesla_dashcam

It's possible I may have missed a step, but the errors will usually tell you what component is missing and from there, you can usually use Google to get the solution. Once installed, run per the directions. I also made sure to use the option "--gpu_type RPi" to insure it runs as fast as possible on the Pi.
