### ISSUE TITLE
Release v0.1.17 - Beta

### ISSUE THREAD

**Issue by ehendrix23** [ehendrix23/tesla_dashcam#143]
Creating this issue to track any issues with v0.1.17 beta releases.

**Comment by ehendrix23** [comment]
First beta release has been made available: v0.1.17b1: https://github.com/ehendrix23/tesla_dashcam/releases/edit/v0.1.17b1

**Comment by mattenz** [comment]
What is --sentry_offset meant to do? The outputed file doesn't seem any different to not using it. I had assumed based on the description that it would cut the outputed video to be just around the time of the event in the JSON file. I've put the debug log file on Pastebin since I can't get the formatting for it right here: https://pastebin.com/eLk7tUbR

**Comment by ehendrix23** [comment]
> What is --sentry_offset meant to do? The outputed file doesn't seem any different to not using it. I had assumed based on the description that it would cut the outputed video to be just around the time of the event in the JSON file. I've put the debug log file on Pastebin since I can't get the formatting for it right here: https://pastebin.com/eLk7tUbR

It works in combination with --start_offset and --end_offset.
Next beta release will have defaults for start_offset and end_offset if sentry_offset is provided (30 and 60 seconds respectively).

**Comment by spkane** [comment]
Posting a beta link that should work for everyone:

https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.17b2

**Comment by ehendrix23** [comment]
FYI, in the mean time v0.1.17b3 and v0.1.17b4 have been released:
https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.17b4

**Comment by x140l31** [comment]
Hi, this version returns an error

`❯ /Applications/tesla_dashcam --version
tesla_dashcam v0.1.17
❯ /Applications/tesla_dashcam

Traceback (most recent call last):
  File "tesla_dashcam/tesla_dashcam.py", line 4511, in <module>
  File "tesla_dashcam/tesla_dashcam.py", line 3815, in main
  File "shutil.py", line 1390, in which
  File "posixpath.py", line 152, in dirname
TypeError: expected str, bytes or os.PathLike object, not NoneType
[47138] Failed to execute script 'tesla_dashcam' due to unhandled exception!`

**Comment by ehendrix23** [comment]
Thank you,

v0.1.18 has been released with fix.
