### ISSUE TITLE
Automate with teslausb

### ISSUE THREAD

**Issue by bahree** [ehendrix23/tesla_dashcam#46]
I recently got [Teslausb](https://github.com/marcone/teslausb) setup running on a pi in the car which copies the files over to my NAS (synology) and I was curious if there is any thoughts on how could one possibly combine both of these? So once the files are copied to the NAS, something like this an kick off and stitch the files together - all automatically. Appreciate any thoughts. Thanks.

**Comment by ehendrix23** [comment]
Right now when using --monitor it looks for a volume that has been mounted with TeslaCam folder on it. 
What you could do is create a link on your NAS on the root volume with name TeslaCam. That link then points to the actual location where you drop the files on.

Then, just before copying the files you unlink (or rename) that. Copy the files, to the actual location, and then create the link again. And just make sure there is at least 10 seconds or so (which just getting the files copied over should be suffice in most cases) between removing and then creating the folder.

What it does is it gets all volumes mounted and checks if any have TeslaCam folder. So if you mount a a volume on /MyVolumes/Tesla then it will check if there is a /MyVolumes/Tesla/TeslaCam folder. If there is processing will start. Once processing is done it will wait until /MyVolumes/Tesla/TeslaCam is not there anymore, and once it isn't there anymore it will go back into waiting.

On my ToDo is to make it so that it can check folder(s) to determine if anything has been changed or not. But haven't started working on that yet as I also need to make sure then that whatever all is being copied is indeed finished.

**Comment by ehendrix23** [comment]
Marking as duplicate to allow for monitoring of persistent storage
